"""
ObfuscationArena: Explain obfuscated code at increasing levels.

Environment concept:
  The model is given obfuscated Python code and must explain what it does.
  The code is generated by taking simple, readable functions and obfuscating
  them (renaming variables to single letters, removing whitespace, combining
  expressions). The model must identify the original intent.

  Why: explaining obfuscated code requires deep semantic understanding —
  the model cannot pattern-match on variable names or structure. It must
  reason about what the code *does*, not what it *looks like*.

Verification:
  - Check if the explanation mentions key concepts from the original code
    (function name, operations, return value).
  - Partial credit for each keyword found.

Reward design:
  fraction of key_concepts mentioned in the explanation.
"""

from __future__ import annotations

import random
import re
from typing import Any, Optional

from iloptimus.core.rl_factory.core.base import Problem
from iloptimus.core.rl_factory.core.batch_base import BatchEnvBase
from iloptimus.core.rl_factory.core.verifier import Verifier, VerifierResult


# ---------------------------------------------------------------------------
# Problem bank — original (readable) code + key concepts
# ---------------------------------------------------------------------------

_ORIGINAL_SNIPPETS = [
    {
        "original_code": (
            "def is_even(n):\n"
            "    if n % 2 == 0:\n"
            "        return True\n"
            "    else:\n"
            "        return False\n"
        ),
        "key_concepts": ["even", "modulo", "2", "return", "true", "false"],
        "description": "checks if a number is even",
    },
    {
        "original_code": (
            "def factorial(n):\n"
            "    result = 1\n"
            "    for i in range(1, n + 1):\n"
            "        result = result * i\n"
            "    return result\n"
        ),
        "key_concepts": ["factorial", "multiply", "loop", "range", "return", "product"],
        "description": "computes the factorial of n",
    },
    {
        "original_code": (
            "def max_of_list(lst):\n"
            "    best = lst[0]\n"
            "    for x in lst:\n"
            "        if x > best:\n"
            "            best = x\n"
            "    return best\n"
        ),
        "key_concepts": ["max", "maximum", "list", "loop", "compare", "return"],
        "description": "finds the maximum value in a list",
    },
    {
        "original_code": (
            "def reverse_string(s):\n"
            "    result = ''\n"
            "    for ch in s:\n"
            "        result = ch + result\n"
 "    return result\n"
        ),
        "key_concepts": ["reverse", "string", "loop", "concat", "return", "character"],
        "description": "reverses a string",
    },
    {
        "original_code": (
            "def count_vowels(s):\n"
            "    count = 0\n"
            "    for ch in s:\n"
            "        if ch in 'aeiou':\n"
            "            count = count + 1\n"
            "    return count\n"
        ),
        "key_concepts": ["count", "vowel", "string", "loop", "aeiou", "return"],
        "description": "counts the vowels in a string",
    },
    {
        "original_code": (
            "def sum_list(lst):\n"
            "    total = 0\n"
            "    for x in lst:\n"
            "        total = total + x\n"
            "    return total\n"
        ),
        "key_concepts": ["sum", "list", "loop", "add", "total", "return"],
        "description": "sums all elements in a list",
    },
    {
        "original_code": (
            "def is_prime(n):\n"
            "    if n < 2:\n"
            "        return False\n"
            "    for i in range(2, n):\n"
            "        if n % i == 0:\n"
            "            return False\n"
            "    return True\n"
        ),
        "key_concepts": ["prime", "divisible", "modulo", "loop", "range", "return"],
        "description": "checks if a number is prime",
    },
    {
        "original_code": (
            "def gcd(a, b):\n"
            "    while b != 0:\n"
            "        temp = b\n"
            "        b = a % b\n"
            "        a = temp\n"
            "    return a\n"
        ),
        "key_concepts": ["gcd", "modulo", "while", "swap", "return", "euclid"],
        "description": "computes the greatest common divisor",
    },
]


def _obfuscate(code: str, rng: random.Random) -> str:
    """Obfuscate Python code: rename vars, collapse whitespace."""
    # Rename function name to a single letter
    func_match = re.match(r"def (\w+)\(([^)]*)\):", code)
    if func_match:
        orig_name = func_match.group(1)
        params = [p.strip() for p in func_match.group(2).split(",") if p.strip()]
        new_name = "f"
        # Map params to single letters
        param_map = {}
        for i, p in enumerate(params):
            param_map[p] = chr(ord("a") + i)
        # Find all local variables (assignments)
        local_vars = set(re.findall(r"(\w+)\s*=", code))
        local_vars.discard(orig_name)
        for lv in local_vars:
            if lv not in param_map:
                param_map[lv] = chr(ord("n") + len(param_map))
        # Replace in code
        result = code.replace(orig_name, new_name)
        for old, new in sorted(param_map.items(), key=lambda x: -len(x[0])):
            result = re.sub(r"\b" + re.escape(old) + r"\b", new, result)
        # Collapse whitespace: remove blank lines, reduce indentation
        lines = [ln.strip() for ln in result.split("\n") if ln.strip()]
        result = ";".join(lines)
        return result
    return code


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------


def obfuscation_arena_generator(seed: int) -> Problem:
    """Generate an ObfuscationArena problem: explain obfuscated code."""
    rng = random.Random(seed)
    snippet = rng.choice(_ORIGINAL_SNIPPETS)
    original_code = snippet["original_code"]
    obfuscated_code = _obfuscate(original_code, rng)
    key_concepts = snippet["key_concepts"]

    prompt = (
        f"Explain what the following obfuscated Python code does.\n\n"
        f"```\n{obfuscated_code}\n```\n\n"
        f"Describe the function's purpose, the operations it performs, "
        f"and what it returns.\n"
        f"Format your answer as: EXPLANATION: <your explanation>"
    )

    difficulty = 0.3 + (len(key_concepts) * 0.05)
    difficulty = min(0.9, difficulty)

    return Problem(
        id=f"obfuscation_arena_{seed}",
        prompt=prompt,
        difficulty=difficulty,
        metadata={
            "original_code": original_code,
            "obfuscated_code": obfuscated_code,
            "key_concepts": key_concepts,
            "description": snippet["description"],
        },
        token_budget=512,
        source="obfuscation_arena_generator",
    )


obfuscation_arena_generator.__test__ = False  # type: ignore[attr-defined]


# ---------------------------------------------------------------------------
# Verifier
# ---------------------------------------------------------------------------


class ObfuscationArenaVerifier(Verifier):
    """Verify an obfuscation explanation: check for key concepts.

    reward = fraction of key_concepts found in the explanation.
    """

    def __init__(self, key_concepts: list[str]):
        super().__init__()
        self._key_concepts = [c.lower() for c in key_concepts]

    def verify(self, response: str) -> VerifierResult:
        explanation_match = re.search(
            r"EXPLANATION\s*:\s*(.+)", response, re.IGNORECASE | re.DOTALL
        )
        if explanation_match:
            text = explanation_match.group(1).lower()
        else:
            text = response.lower()

        found = 0
        for concept in self._key_concepts:
            if concept in text:
                found += 1

        fraction = found / len(self._key_concepts) if self._key_concepts else 0.0
        correct = fraction >= 0.6

        return VerifierResult(
            correct=correct,
            score=fraction,
            partial_credit={
                "concepts_found": float(found),
                "concepts_total": float(len(self._key_concepts)),
                "concept_fraction": fraction,
            },
            diagnostics=(
                f"concepts={found}/{len(self._key_concepts)} "
                f"fraction={fraction:.2f}"
            ),
        )


# ---------------------------------------------------------------------------
# Environment
# ---------------------------------------------------------------------------


class ObfuscationArenaEnv(BatchEnvBase):
    """ObfuscationArena: explain obfuscated code.

    Batch-aware: N parallel attempts; reward = best explanation.
    """

    __test__ = False

    def __init__(
        self,
        problems: Optional[list[Problem]] = None,
        problem_generator=None,
        reward_config=None,
        anti_pattern_detector=None,
        render_mode=None,
        batch_size: int = 16,
    ):
        if problems is None and problem_generator is None:
            problem_generator = obfuscation_arena_generator
        super().__init__(
            problems=problems,
            problem_generator=problem_generator,
            reward_config=reward_config,
            anti_pattern_detector=anti_pattern_detector,
            render_mode=render_mode,
            batch_size=batch_size,
        )

    def _make_verifier(self, problem: Problem) -> Verifier:
        return ObfuscationArenaVerifier(
            key_concepts=problem.metadata["key_concepts"],
        )

    def _check_format(self, response: str) -> float:
        if re.search(r"EXPLANATION\s*:", response, re.IGNORECASE):
            return 1.0
        if len(response.strip()) > 20:
            return 0.5
        return 0.0

    def _aggregate_scores(self, per_sample: list[dict]) -> dict:
        scores = [s["verifier_score"] for s in per_sample]
        corrects = [s["correct"] for s in per_sample]
        best_score = max(scores) if scores else 0.0
        any_correct = any(corrects)
        return {
            "best_score": best_score,
            "any_correct": any_correct,
            "correct_count": sum(corrects),
            "mean_score": sum(scores) / len(scores) if scores else 0.0,
            "reward": best_score,
            "correct": any_correct,
            "diagnostics": (
                f"Best={best_score:.2f} Correct={sum(corrects)}/{len(per_sample)} "
                f"Mean={sum(scores)/len(scores) if scores else 0:.2f}"
            ),
        }

    def _extract_answer(self, response: str) -> str:
        match = re.search(r"EXPLANATION\s*:\s*(.+?)(?:\n|$)", response, re.IGNORECASE | re.DOTALL)
        return match.group(1).strip() if match else response
